name: store
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  api:
    path: ./packages/api/service
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  bloc_notification: ^1.1.2+1
  device_apps: ^2.2.0
  permission_handler: ^10.3.0
  lottie: ^2.3.2
  nested: ^1.0.0
  overlay_support: ^2.1.0
  provider: ^6.0.5
  intl_utils: ^2.8.2
  dio: ^5.2.1
  path: ^1.8.2
  # path_provider: ^2.0.15
  filesize: ^2.0.1
  percent_indicator: ^4.2.3
  # app_installer: ^1.1.0
  openapi_generator_annotations: ^4.10.0
  open_filex: ^4.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  openapi_generator: ^4.10.0

flutter:
  # generate: true
  uses-material-design: true

  assets:
    - assets/

flutter_intl:
  enabled: true
  class_name: S
  main_locale: vi
  arb_dir: lib/l10n/
  template-arb-file: intl_en.arb
  output-localization-file: l10n.dart
  output_dir: lib/l10n/generated
  use_deferred_loading: true
  synthetic-package: false
